Repository nucypher/nucypher-monitor, pull requests merged in 2020-07, with the labels that each got.

#66 Fix favicon to HR png version
  monitor/assets/favicon.ico
Labels: enhancement

#67 Add notes to README on let's encrypt certificates for docker
  README.md
Labels: documentation

#70 Update nucypher-monitor to be compatible with latest version of nucypher - 2.1.0b12
  Pipfile.lock
  README.md
  dev-requirements.txt
  monitor/cli/main.py
  monitor/crawler.py
  requirements.txt
  tests/test_crawler.py
  tests/test_dashboard.py
  tests/utilities.py
Labels: dependencies
